version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: english_trainer_db

    environment:
      POSTGRES_DB: english_trainer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: