"""add spaced repetition fields

Revision ID: 6daace8d12fb
Revises: 82454ee88f48
Create Date: 2026-06-23 15:34:18.242352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6daace8d12fb'
down_revision: Union[str, Sequence[str], None] = '82454ee88f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Добавляем колонки со значениями по умолчанию
    op.add_column('words', sa.Column('strength', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('words', sa.Column('interval_days', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('words', sa.Column('next_review', sa.DateTime(), nullable=True))
    op.add_column('words', sa.Column('last_review', sa.DateTime(), nullable=True))
    op.add_column('words', sa.Column('review_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('words', sa.Column('correct_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('words', sa.Column('wrong_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'wrong_count')
    op.drop_column('words', 'correct_count')
    op.drop_column('words', 'review_count')
    op.drop_column('words', 'last_review')
    op.drop_column('words', 'next_review')
    op.drop_column('words', 'interval_days')
    op.drop_column('words', 'strength')
    # ### end Alembic commands ###
