"""add level to words

Revision ID: f5e8100568d8
Revises: b520d1a47534
Create Date: 2026-06-23 21:43:28.894542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e8100568d8'
down_revision: Union[str, Sequence[str], None] = 'b520d1a47534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'level')
    # ### end Alembic commands ###
